sudo: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"

cache:
  directories:
    - node_modules
notifications:
  email: false

script:
  - npm run lint
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      after_success:
        - npm i -g semantic-release @semantic-release/exec && semantic-release
branches:
  only:
    - master
