sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
matrix:
  include:
    - node_js: "6"
    - node_js: "4"
    - node_js: "0.12"
script:
  - npm test
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master
